
networks:
  microservices-net:
    driver: bridge

volumes:
  commercial-db-data:
  logistics-db-data:

services:
  # ── Microservices ───────────────────────────────────────────────
  ordering:
    build: ./ordering
    ports:
      - "8080:8080"
    env_file:
      - ./ordering/.env

  billing:
    build: ./billing
    ports:
      - "3002:3002"
    env_file:
      - ./billing/.env

  inventory:
    build: ./inventory
    ports:
      - "3003:3003"
    env_file:
      - ./inventory/.env

  shipping:
    build: ./shipping
    ports:
      - "3004:3004"
    env_file:
      - ./shipping/.env

  notification:
    build: ./notification
    ports:
      - "3005:3005"
    env_file:
      - ./notification/.env
  # ── PostgreSQL Comercial ────────────────────────────────────
  commercial-db:
    image: postgres:16
    container_name: commercial-db
    networks: [microservices-net]
    restart: unless-stopped
    environment:
      POSTGRES_DB: commercial_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - commercial-db-data:/var/lib/postgresql/data
      - ./infra/commercial.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d commercial_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ── PostgreSQL Logística ────────────────────────────────────
  logistics-db:
    image: postgres:16
    container_name: logistics-db
    networks: [microservices-net]
    restart: unless-stopped
    environment:
      POSTGRES_DB: logistics_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - logistics-db-data:/var/lib/postgresql/data
      - ./infra/logistics.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d logistics_db"]
      interval: 10s
      timeout: 5s
      retries: 10